### ISSUE TITLE
Problem updating Ethoscope to master branch

### ISSUE THREAD

**Issue by pgorelik** [gilestrolab/ethoscope#164]
Hello,

Whenever I try to update the Ethoscope to the latest `master` branch, the device_server stops and the device goes offline. I then have to manually change the branch back to `dev` from within the device to get it to work. When trying to run the latest `master` branch, I get the following status:

```
[alarm@ETHOSCOPE013 ethoscope-device]$ systemctl status ethoscope_device
* ethoscope_device.service - Ethoscope device server
     Loaded: loaded (/usr/lib/systemd/system/ethoscope_device.service; enabled; vendor preset: disabled)
     Active: activating (auto-restart) (Result: exit-code) since Wed 2021-10-06 19:43:55 UTC; 1s ago
    Process: 3061 ExecStart=/usr/bin/python3 /opt/ethoscope-device/src/scripts/device_server.py -D (code=exited, status=1/FAILURE)
   Main PID: 3061 (code=exited, status=1/FAILURE)
```
My node is an old i5 PC and the Ethoscope runs on a rPi 3B+. After I burn a new SD card using the ISO and set it up, the status looks like in the picture below. However, as soon as I try to update the device to the most recent `master` branch, the device goes offline, and I get the error shown above.

![image](https://user-images.githubusercontent.com/6675235/136278978-f34e9780-8299-4c2f-b79d-45e8e7d4e2fa.png)

If I update the device but stay on the `dev` branch, I get an error when I try to run the **OptomotorSleepDepriver** interactor.
![image](https://user-images.githubusercontent.com/6675235/136283515-2a51560e-3831-4ea0-910e-bcd3a322a0b6.png)

```
Sorry there has been an error: Traceback (most recent call last): File "/opt/ethoscope-device/src/ethoscope/web_utils/control_thread.py", line 485, in run self._start_tracking(cam, result_writer, rois, TrackerClass, tracker_kwargs, hardware_connection, StimulatorClass, stimulator_kwargs) File "/opt/ethoscope-device/src/ethoscope/web_utils/control_thread.py", line 342, in _start_tracking self._monit.run(result_writer, self._drawer) File "/opt/ethoscope-device/src/ethoscope/core/monitor.py", line 139, in run raise e File "/opt/ethoscope-device/src/ethoscope/core/monitor.py", line 117, in run data_rows = track_u.track(t, frame) File "/opt/ethoscope-device/src/ethoscope/core/tracking_unit.py", line 96, in track interact, result = self._stimulator.apply() File "/opt/ethoscope-device/src/ethoscope/stimulators/stimulators.py", line 56, in apply interact, result = self._decide() File "/opt/ethoscope-device/src/ethoscope/stimulators/sleep_depriver_stimulators.py", line 232, in _decide out, dic = super(OptomotorSleepDepriver, self)._decide() File "/opt/ethoscope-device/src/ethoscope/stimulators/sleep_depriver_stimulators.py", line 135, in _decide if random.uniform(0,1) <= self._p: TypeError: '<=' not supported between instances of 'float' and 'str' 

```

So, neither the `master` branch nor the `dev` branch is workable for me right now. Do you have any advice on what might be wrong?

Thanks,
Pavel

**Comment by pgorelik** [comment]
Hi, 

I was attempting to use the 'OptoMotorSleepDepriver' interactor, which does not have a stimulus probability field. I see that 'SleepDepStimulator' has this option -- is this the interactor I should be using for sleep deprivation? Has 'OptoMotorSleepDepriver' been depricated? With 'SleepDepStimulator' my motors do not turn; however, this could be because I am still using old Arduino code. I will check that next.
